source :rubygems

gem "sinatra"

gem "slim"

gem "sass"

gem "dm-core"

gem "dm-migrations"

gem "thin"

gem "pg"

gem "dm-sqlite-adapter", :group => :development

gem "dm-postgres-adapter", :group => :production
